BUNDLE_NAME = MariePrefs

MariePrefs_FILES = MarieVC.m
MariePrefs_CFLAGS = -fobjc-arc
MariePrefs_LIBRARIES = gcuniversal
MariePrefs_FRAMEWORKS = UIKit
MariePrefs_PRIVATE_FRAMEWORKS = Preferences OnBoardingKit
MariePrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk