include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = MariePrefs

MariePrefs_FILES = MARRootListController.m
MariePrefs_CFLAGS = -fobjc-arc
MariePrefs_LIBRARIES = gcuniversal
MariePrefs_FRAMEWORKS = UIKit
MariePrefs_PRIVATE_FRAMEWORKS = Preferences
MariePrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS_MAKE_PATH)/bundle.mk